[project]
name = "flask-vercel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.0",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
