name: daily-commit

on:
  schedule:
    # Use https://crontab.guru/ to format this section (UTC based)
    - cron: "0 4 * * *" # 04:00 am UTC
  workflow_dispatch:
jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add commit with raymondbrian.gorospe@straive.com
        run: |
          # Setting Git Config
          git config --global user.name "GitHub Actions"
          git config --global user.email "raymondbrian.gorospe@straive.com"
          # Create a file and modify existing file
          echo "Daily commit on $(date)" >> daily-commit.txt
          # Staging, commit, and push
          git add daily-commit.txt
          git commit -m "Daily automated commit"
          git push origin main